### ISSUE TITLE
Error when wget --insecure 

### ISSUE THREAD

**Issue by txsastre** [vacosta94/VirtBKP#3]
wget --insecure "https://ovirt.infratic.com/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA"

this parameter "--insecure" does not exist.

I used wget --no-check-certificate instead, and changed the name of the downloaded file.

**Comment by vacosta94** [comment]
You're right, that parameter is from "curl", i'll update that, thanks
