### ISSUE TITLE
[ERROR] Connection to oVirt API has failed

### ISSUE THREAD

**Issue by txsastre** [vacosta94/VirtBKP#4]
I've noticed that if you are not inside the directory /opt/VirtBKP/ and if I try to make a backup I receive this error "[ERROR] Connection to oVirt API has failed" is it normal ?

**Comment by vacosta94** [comment]
Do you use relative path or full path for CA file in your configuration file?

That error can be caused if the CA file could not be found

**Comment by txsastre** [comment]
ok I see the problem.

thanks !
