### ISSUE TITLE
error concatenate function

### ISSUE THREAD

**Issue by bylli79** [vacosta94/VirtBKP#6]
Hello,
at the "Attach snap disk to bkpvm" step I get the following error:
urlattach = url + "/ v3 / vms /" + bkpid + "/ disks /"
can not concatenate 'str' and 'NoneType' objects

What can I do?

Thank you

**Comment by bylli79** [comment]
The error is in the function:
bkpvm = get_id_vm (bkpvm) 
which returns null.
What should I set in bkpvm?

Thank you

**Comment by vacosta94** [comment]
Hi, that error could apper if your `bkpvm`  name is not correct
The `bkpvm` parameter it's used to identify the vm that the disk would be attached to

**Comment by bylli79** [comment]
sorry,
I can not understand what the bkpvm is.

Thank you

**Comment by vacosta94** [comment]
bkpvm is the where you ran the script. So, you have to put the of that virtual machine in that parameter, i use that name in order identify the VM then attach the virtual disk to it

**Comment by bylli79** [comment]
Do I need to create a virtual machine without disks to be used as a backup?
Every time I make a backup, a disk snapshot is created on this machine that I create?

Thank you

**Comment by vacosta94** [comment]
You need to create a virtual machine to make backup in it, this VM should be installed with CentOS7 and you should ran the script on it, so, if this VM's name is "backupvm", your bkpvm parameter have to be "backupvm".

For instance, If you want to create a backup of a VM called "webvm", the proccess would be the next:
 - Run the script on "backupvm" with all the required parameters
 - The script goint to connect to oVirt's Api and it going to create a snapshot of "webvm" VM
 - webvm's disks based on the snapshot would be mounted to "backupvm" so it can create a qcow image of each webvm's disk
 - After backup finished webvm's disks going to be unmounted of backupvm 
 - Then webvm's snapshot previosly created going to be deleted

**Comment by marciofoz** [comment]
Hi !
I have the same issue here, please check my bkpvm name:

hostname 
divisa.unila

hostnamectl 
Static hostname: divisa.unila

default.conf
[bkp]
url     = https://engineovirt.unila/ovirt-engine/api
user        = admin
password    = 123456789
ca_file     = ca.crt
bkpvm       = divisa.unila                                                                                                                                                                                         
bckdir      = /data/

backup_vm.py /opt/VirtBKP/default.conf test-divisa
[OK] Connection to oVIrt API success https://engineovirt.unila/ovirt-engine/api
[INFO] Trying to create snapshot of VM: 6ac090d5-8b22-4d6f-a5a7-a4b4cd71b1a8
[OK] Snapshot created
[INFO] Trying to create a qcow2 file of disk cd1bad37-90fe-4d4b-a923-ee9ceb6436c7
[INFO] Attach snap disk to bkpvm
Traceback (most recent call last):
  File "/opt/VirtBKP/backup_vm.py", line 242, in <module>
    main()
  File "/opt/VirtBKP/backup_vm.py", line 237, in main
    backup(vmid,snapid,disk_id,bkpvm)
  File "/opt/VirtBKP/backup_vm.py", line 201, in backup
    attach_disk(bkpvm,disk_id,snapid)
  File "/opt/VirtBKP/backup_vm.py", line 117, in attach_disk
    urlattach = url+"/v3/vms/"+bkpid+"/disks/"
TypeError: cannot concatenate 'str' and 'NoneType' objects

I'm using oVirt 4.1.5.2 and bpkvm is Centos 7.5.
Thanks.

**Comment by vacosta94** [comment]
divisa.unila is your hostname, you have to use the vm name instead, i mean the name that you see in the ovirt engine console

**Comment by marciofoz** [comment]
Hi @vacosta94.
It's working now.
Thank you.

**Comment by vacosta94** [comment]
Good to know
