### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by babarnazmi** [vacosta94/VirtBKP#8]
I am trying to take backup of one of my machine, but getting below error
I can see snapshot created, but no data in backup folder as script stopped due to TypeError

[root@virtnode01 VirtBKP]# /opt/VirtBKP/backup_vm.py /opt/VirtBKP/default.conf webmail
[OK] Connection to oVIrt API success https://virtnode01/ovirt-engine/api
[INFO] Trying to create snapshot of VM: 734f48fe-118e-406a-8887-ab7a01d0fe80
[INFO] Waiting until snapshot creation ends
[INFO] Waiting until snapshot creation ends
[OK] Snapshot created
[INFO] Trying to create a qcow2 file of disk 35f5e2ce-fca3-4ad0-8fa3-6dd416718cd7
[INFO] Attach snap disk to bkpvm
Traceback (most recent call last):
  File "/opt/VirtBKP/backup_vm.py", line 242, in <module>
    main()
  File "/opt/VirtBKP/backup_vm.py", line 237, in main
    backup(vmid,snapid,disk_id,bkpvm)
  File "/opt/VirtBKP/backup_vm.py", line 201, in backup
    attach_disk(bkpvm,disk_id,snapid)
  File "/opt/VirtBKP/backup_vm.py", line 117, in attach_disk
    urlattach = url+"/v3/vms/"+bkpid+"/disks/"
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by paborko** [comment]
Exactly the same problem:

[INFO] Trying to create snapshot of VM: dc59bca1-cc95-437f-950e-ea0bfc485ae4
[INFO] Waiting until snapshot creation ends
[INFO] Waiting until snapshot creation ends
[OK] Snapshot created
[INFO] Trying to create a qcow2 file of disk ca52b9f3-8964-4852-b622-891db15bc5b4
[INFO] Attach snap disk to bkpvm
Traceback (most recent call last):
  File "./backup_vm.py", line 6, in <module>
    b.main()
  File "/opt/VirtBKP/backup_vm_last.py", line 241, in main
    self.backup(self.vmid,self.snapid,disk_id,self.bkpvm)
  File "/opt/VirtBKP/backup_vm_last.py", line 209, in backup
    self.attach_disk(bkpvm,disk_id,snapid)
  File "/opt/VirtBKP/backup_vm_last.py", line 120, in attach_disk
    urlattach = self.url+"/v3/vms/"+bkpid+"/disks/"
TypeError: cannot concatenate 'str' and 'NoneType' objects

Any suggestion?

**Comment by paborko** [comment]
solved here: https://github.com/vacosta94/VirtBKP/issues/6

**Comment by vacosta94** [comment]
Solver on #6
